### ISSUE TITLE
Simple example: builder.Register<Foo>() doesn't compile in C# Net 2.0

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#78]
_From [dh...@optionmetrics.com](https://code.google.com/u/109227097061216286634/) on August 19, 2008 02:24:02_

Create new project in VS2005 C# Net 2.0:
ContainerBuilder builder = new ContainerBuilder();
builder.Register<Foo>().As<IFoo>();

Does not compile.
"Register<T>" is not a member of ContainerBuilder.
Build 1.2.7.397-Net2.0

Does the documentation need to be updated?

_Original issue: http://code.google.com/p/autofac/issues/detail?id=77_
